#ifndef AMOUNTOFELEMENTSAPPEARINGSEVERALTIMES_H_INCLUDED
#define AMOUNTOFELEMENTSAPPEARINGSEVERALTIMES_H_INCLUDED

int amountOfElementsAppearingSeveralTimes(int array[], int sizeOfPart);

#endif // AMOUNTOFELEMENTSAPPEARINGSEVERALTIMES_H_INCLUDED
