#ifndef LONGESTPARTWITHTHESAMEELEMENTS_H_INCLUDED
#define LONGESTPARTWITHTHESAMEELEMENTS_H_INCLUDED

int lengthOfTheLongestPartWithTheSameElemenets(int array[], int sizeOfPart);

#endif // LONGESTPARTWITHTHESAMEELEMENTS_H_INCLUDED
