#ifndef MAXIMALSINGLEELEMENTOFARRAY_H_INCLUDED
#define MAXIMALSINGLEELEMENTOFARRAY_H_INCLUDED

int maximalSingleElementOfArray(int array[], int sizeOfPart);

#endif // MAXIMALSINGLEELEMENTOFARRAY_H_INCLUDED
