#ifndef LASTEVENPOSITIVENUMBERTOTHEEND_H_INCLUDED
#define LASTEVENPOSITIVENUMBERTOTHEEND_H_INCLUDED

void lastEvenPositiveNumberToTheEnd(int number, int array[], int sizeOfPart);

#endif // LASTEVENPOSITIVENUMBERTOTHEEND_H_INCLUDED
