#ifndef MINIMALOFELEMENTSAPPEARINGSEVERALTIMES_H_INCLUDED
#define MINIMALOFELEMENTSAPPEARINGSEVERALTIMES_H_INCLUDED

int minimalElementAppearingSeveralTimes(int array[], int sizeOfPart);

#endif // MINIMALOFELEMENTSAPPEARINGSEVERALTIMES_H_INCLUDED
